### ISSUE TITLE
中文日志utf-8编码问题

### ISSUE THREAD

**Issue by yyngfive** [AmiyaBot/Amiya-Bot-core#1]
我使用README提供的代码运行我自己的频道机器人，在向机器人发出指令后logging模块报错
`UnicodeEncodeError: 'gbk' codec can't encode character '\u05e9' in position 87: illegal multibyte sequence`，并且amiyabot.log文件中中文乱码，我自己在`log.py`的`file_handler = TimedRotatingFileHandler`中添加了`encoding='utf-8'`暂时解决了这一问题，还请官方能修复一下

**Comment by vivien8261** [comment]
fixed [87cf911](https://github.com/AmiyaBot/Amiya-Bot-core/commit/87cf91135bc4a01f998755307158e19a48409112)
