### ISSUE TITLE
建议提供一种可以透传的Message响应函数

### ISSUE THREAD

**Issue by hsyhhssyy** [AmiyaBot/Amiya-Bot-core#4]
我在开发的时候，遇到这样一种需求
我做了一个功能，可以记录群内所有人说的话并生成词云，为了让他能够响应任意话语，最初他的开头是这样的：
```
async def any_talk(data: Message):
    return True

@bot.on_message(verify=any_talk, check_prefix=False)
async def _(data: Message):
    ....
```

这就产生了一个问题，他短路了所有的Message，任何其他事件，包括来自其他插件的事件，只要没有level>1，都无法执行了。

我在想，是否需要提供一个功能，让某个message事件函数不会短路其他的事件，这个函数执行完以后，会继续执行其他的注册函数。

我自己尝试了两个版本，一个是设置为level可以为负数，但是这样就影响了Verify的len重载（很奇怪不知道为什么要重载这个函数），我担心有side effect。
另一个是给on_message提供一个bypass布尔值参数，但是严重影响handler的逻辑，并且和level的语义冲突。
不管哪个，都不是很好，所以都没有提交PR。

所以我这里提一个小小的功能建议，希望大佬们考虑一下。

**Comment by vivien8261** [comment]
如果只是想获取 message 且不影响后续的功能校验的话，可以看看生命周期的 [before_bot_reply](https://www.amiyabot.com/develop/advanced/lifeCycle.html#before-bot-reply)，返回 True 或 None 就可以当做是一个拦截器使用。

**Comment by hsyhhssyy** [comment]
> 

看到这个，我突然想到一个惊天Trick，我把功能放在verify函数里就行了

**Comment by hsyhhssyy** [comment]
算上上面提到的这些，我已经找到多个解决方案了，暂时应该不需要改什么了，我关掉这个issue了
