### ISSUE TITLE
修复 Onebot v11 适配器主动发送消息时空字段导致发送失败的问题

### ISSUE THREAD

**Issue by usaginya** [AmiyaBot/Amiya-Bot-core#95]
## 问题描述

- 在使用 onebot v11 适配器，兔兔主动向私聊和群内发送消息时，出现发送失败的情况，影响范围有：微博推送、定时提醒等自动发送消息的插件
- 这里使用 lagrange 的 onebot v11 api 搭载作为示例，主动发送消息时控制台的日志内容：
![发送到onebot的错误消息参数](https://github.com/AmiyaBot/Amiya-Bot-core/assets/16422300/095dd751-9371-49d5-b295-55ae29b9aaa1)

- 在消息中的情况：
![兔兔不能主动发出消息](https://github.com/AmiyaBot/Amiya-Bot-core/assets/16422300/c9561100-9a3e-42b0-ab84-2ed912c5d113)

## 问题分析
- 从日志推测，onebot api 接收到了 `user_id` 参数，但获得了空值，导致 onebot 处理要发送的消息时出错
- 以定时提醒插件为问题跟踪示例，找到主动发送消息的适配器接口 `send_message`
- 创建发送消息的流程：创建新的消息链 `Chain` → 构建消息 → 调用适配器实例的方法 `send_message` 发送消息
- 由于没有另外提供 `user_id` 的值，创建的消息链 `Chain` 中默认为空字符串，定位到 onebot v11 适配器的 `send_message` 方法中也没有处理空值参数，最终导致发送主动消息时失败
![定时提醒插件示例](https://github.com/AmiyaBot/Amiya-Bot-core/assets/16422300/79b8ca29-92d7-4eca-874b-c1e9c3914885)

## 解决问题
- 因为影响到多个插件发送主动消息的方法，从插件方面适配解决问题不符合实际，因此选择对默认的 onebot v11 适配器方法进行空值处理，来解决问题（参考 onebot v11 api - [send_msg](https://github.com/botuniverse/onebot-11/blob/master/api/public.md#send_msg-%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF)）
- 通过把返回中的空值项移除，从而解决空值项导致发送消息失败的问题，又不影响有值存在时的情况
- 对空值移除处理后的返回值测试：
- - `user_id` 存在值的情况
- - ![测试user_id有值](https://github.com/AmiyaBot/Amiya-Bot-core/assets/16422300/9dc4b3e3-47ad-48f6-adfd-6f95f4865caf)

- - `user_id` 存在空值的情况
- - ![测试user_id空值](https://github.com/AmiyaBot/Amiya-Bot-core/assets/16422300/c3c59208-4d40-41ad-9495-95ac0a5a1c35)

- - `user_id` 不存在值的情况
- - ![测试user_id无值](https://github.com/AmiyaBot/Amiya-Bot-core/assets/16422300/51b0d957-9edb-403b-b4b3-8fd08f1a0a26)

- 根据测试可见空值项已被处理，返回了有用的结果，并且在实际测试使用上解决了消息发送失败的问题
![发送到onebot的正确消息参数](https://github.com/AmiyaBot/Amiya-Bot-core/assets/16422300/5b7c7c6d-38df-4e10-bc25-b1d13dcd2fc5)
![兔兔可以主动发出消息](https://github.com/AmiyaBot/Amiya-Bot-core/assets/16422300/7d50c5ec-b14e-4018-b5d8-6aafaa9bc8f5)

**Comment by vivien8261** [comment]
已合并，感谢支持
